#
# File: .rubocop.yml
# Author: eweb
# Copyright eweb, 2017-2023
# Contents:
#
# Date:          Author:  Comments:
# 28th Oct 2017  eweb     #0008 rubocop
#  3rd Apr 2018  eweb     #0007 rubocop
#  7th Apr 2018  eweb     #0007 rubocop
# 16th Apr 2023  eweb     #0008 enable new cops
# 17th Apr 2023  eweb     #0008 update
#
# https://github.com/bbatsov/rubocop/tree/master/config
#
# rubocop -DES -f html -o rubocop.html
#
plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/SafeNavigation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true

Style/GuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 200

Style/StringLiterals:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300
  Enabled: false

Metrics/BlockLength:
  Max: 300
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

# RubyMotion
Naming/MethodName:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# TODO turn on Style/AccessorMethodName
Naming/AccessorMethodName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

# nothing wrong with fail
Style/SignalException:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# because x == 0 == x.zero? iff x.number?
Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Security/Open:
  Enabled: false

Style/RescueStandardError:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor: # (0.83)
  Enabled: true

Layout/SpaceAroundMethodCallOperator: # (0.82)
  Enabled: true

Lint/DeprecatedOpenSSLConstant: # (0.84)
  Enabled: true

Lint/MixedRegexpCaptureTypes: # (0.85)
  Enabled: true

Lint/RaiseException: # (0.81)
  Enabled: true

Lint/StructNewOverride: # (0.81)
  Enabled: true

Style/ExponentialNotation: # (0.82)
  Enabled: true

Style/HashEachMethods: # (0.80)
  Enabled: true

Style/HashTransformKeys: # (0.80)
  Enabled: true

Style/HashTransformValues: # (0.80)
  Enabled: true

Style/RedundantRegexpCharacterClass: # (0.85)
  Enabled: true

Style/RedundantRegexpEscape: # (0.85)
  Enabled: true

Style/SlicingWithRange: # (0.83)
  Enabled: true
