#
# File: .rubocop.yml
# Author: eweb
# Copyright eweb, 2017-2018
# Contents:
#
# Date:          Author:  Comments:
# 28th Oct 2017  eweb     #0008 rubocop
#  3rd Apr 2018  eweb     #0007 rubocop
#  7th Apr 2018  eweb     #0007 rubocop
#
# https://github.com/bbatsov/rubocop/tree/master/config
#
# rubocop -DES -f html -o rubocop.html
#
AllCops:
  TargetRubyVersion: 2.5

Style/SafeNavigation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/AlignArray:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true

Style/GuardClause:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 200

Style/StringLiterals:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300
  Enabled: false

Metrics/BlockLength:
  Max: 300
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

# RubyMotion
Naming/MethodName:
  Enabled: true

Layout/IndentHash:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# TODO turn on Style/AccessorMethodName
Naming/AccessorMethodName:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

# nothing wrong with fail
Style/SignalException:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# because x == 0 == x.zero? iff x.number?
Style/NumericPredicate:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Security/Open:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/AsciiComments:
  Enabled: false
