#
# File:     dat2html.pl
# Auhtor:   eweb
# Copyright WBT Systems, 1995-2006
# Contents: Convert a .dat file to .html
#

#
# Date:          Author:  Comments
#


use strict;

my $ignore_empty = 0;

sub file_contents($)
  {
    my ($extension) = @_;
    # [0] extension

    if ( $extension eq ".html" )
      {
        return "HTML table of strings";
      }
  }

sub file_banner($$$)
  {
    my ($stem, $filename, $extension) = @_;
    # [0] OUTPUT
    # [1] filename
    # [2] extension

    print OUTPUT "<!--\n\n";
    print OUTPUT "  File: $stem$extension\n";
    print OUTPUT "  Author: eweb\n";
   #print OUTPUT "  Date: ", scalar localtime, "\n";
    print OUTPUT "  *** DO NOT EDIT - CHANGES MAYBE LOST ***\n";
    print OUTPUT "  This file was generated by a perl program.\n";
    print OUTPUT "  Copyright WBT Systems, 1995-", (localtime)[5]+1900, "\n";
    print OUTPUT "  Contents: ", file_contents( $extension ), "\n\n";
    print OUTPUT "-->\n\n";
  }

sub pre_stuff($$)
  {
    my ($stem, $extension) = @_;
    if ( $extension eq ".html" )
      {
        print OUTPUT "<html>\n";
        print OUTPUT "<head>\n";
        print OUTPUT "<title>$stem</title>\n";
        print OUTPUT "</head>\n";
        print OUTPUT "<body>\n";
      }
  }

sub post_stuff($)
  {
    my ($extension) = @_;
    if ( $extension eq ".html" )
      {
        print OUTPUT "</body>\n";
        print OUTPUT "</html>\n";
      }
}

sub main_stuff
  {
    # [0] output filename
    # [1] stem
    # [2] extension
    # [3] pass
    my $infile = $_[1] . ".dat";
    #my $INPUT = $_[1] . ".dat";
    #print "about to open ", $infile, "\n";
    if ( open( INPUT, $infile ) )
      {
        print OUTPUT "<table border=1>\n";
        print OUTPUT "<tr><td>Dat File</td><td>$infile</td></tr>\n";
        while ( <INPUT> )
          {
            if ( /^$/ )
              {
                last;
              }
            elsif ( /^;/ )
              {
                if ( /^;(.*)=(.*)$/ )
                  {
                    print OUTPUT "<tr><td>$1</td><td>$2</td></tr>\n";
                  }
              }
            else
              {
                last;
              }
          }
        print OUTPUT "</table>\n";
        close(INPUT);
      }

    if ( open( INPUT, $infile ) )
      {
        print OUTPUT "<table border=1>\n";
        print OUTPUT "<tr><td>Name</td><td>Number</td><td>String</td></tr>\n";

        my $maxID = 0;
        while ( <INPUT> )
          {
            if ( /^$/ )
              {
                next;
              }
            elsif ( /^;/ )
              {
                next;
              }
            elsif ( /\"([^\"]*)\"\W+([0-9]*)\W+(\"[^\"]*\")/ )
              {
                my $funcname = $1;
                my $strnumber = $2;
                my $strvalue = $3;
                if ( $funcname =~ /\*/ )
                  {
                    $strvalue = "\"\"";
                  }
                if ( $funcname =~ /\~/ )
                  {
                    $funcname = $`;
                  }
                if ( $strnumber == 0 )
                  {
                    $strnumber = $maxID + 1;
                  }
                if ( $strnumber != $maxID + 1 )
                  {
                    die "String ids must be consequetive";
                  }
                if ( $strnumber > $maxID )
                  {
                    $maxID = $strnumber;
                  }
                if ( $_[2] eq ".html" && $_[3] == 0 )
                  {
                    if ( $ignore_empty && $strvalue eq "\"\"" )
                      {
                        next;
                      }
                    elsif ( $funcname =~ /\*/ )
                      {
                        next;
                      }
                    if ( $strvalue =~ /^"(.*)"$/ )
                      {
                        $strvalue = $1;
                        #if ( $strvalue =~ /[^.]$/ )
                        #  {
                        #    $strvalue = $strvalue .".";
                        #  }
                        #print "$strvalue\n";
                        $strvalue =~ s!&!&amp;!g;
                        $strvalue =~ s!<!&lt;!g;
                        $strvalue =~ s!>!&gt;!g;
                        #$strvalue =~ s!"!&quot;!g; # close that "
                        #$strvalue =~ s!'!&apos;!g;
                        $_ = "<tr><td>$funcname</td><td>$strnumber</td><td>$strvalue</td></tr>\n";
                      }
                  }
              }
            print OUTPUT $_;
          }
        print OUTPUT "</table>\n";
        close(INPUT);
      }
    else
      {
        print "Failed to open input file [$infile]\n";
      }
  }

sub whole_lot($$$)
  {
    my ($pathnoext, $extension, $outdir) = @_;
    # [0] stem
    # [1] extension

    my $stem = $pathnoext;
    if ( $stem =~ /([^\\\/]+)$/ )
      {
        $stem = $1;
        #print "Slashes $stem\n";
      }
    else
      {
        #print "No slash $stem\n";
      }

    my $filename = $pathnoext . $extension;
    #print "about to open ", $filename, "\n";
    my $filepath;
    if ( $outdir ne "" )
      {
        $filepath = "$outdir\\$stem$extension";
      }
    else
      {
        $filepath = "$filename";
      }
    #my $OUTPUT = ">$filepath";
    if ( open( OUTPUT, ">$filepath" ) )
      {
        file_banner( $stem, $filename, $extension );

        pre_stuff( $stem, $extension );

        main_stuff( $filename, $pathnoext, $extension, 0 );

        post_stuff( $extension );
        close( OUTPUT );
      }
    else
      {
        print "Failed to open output file [$filepath]\n";
      }
  }

sub main
  {
    my $stem = $ARGV[0];
    if ( $ARGV[0] eq "" )
      {
        print "TopClass dat2html\n";
        print "Usage: dat2html <stem> <outputdir>\n";
        print " DO NOT specify .dat\n";
        print " Produces stem.html\n";
      }
    else
      {
        whole_lot( $ARGV[0], ".html", $ARGV[1] );
     }
 }

main;
