#
# File: extrainfo.pl
# Author: eweb
# Copyright WBT Systems, 1995-2011
# Contents:
#
# Date:          Author:  Comments:
#  7th Aug 2010  eweb     #12012 Generate ExtraInfo using perl
# 26th Aug 2010  eweb     #00008 Usage, task, case of folders
#  6th Jan 2011  eweb     #12955 Merge from 8.1.0
#  9th Mar 2011  eweb     #00008 Year may be passed in
# 22nd Mar 2011  eweb     #00008 Adapted for 9.0
# 25th Mar 2011  eweb     #00009 Generate hibernate mappings
# 25th Mar 2011  eweb     #00009 Index names too long
# 25th Mar 2011  eweb     #00009 Mix up between WRegistrationRequest_Extra and WRegistrationRequest_UExtra
#  4th Apr 2011  eweb     #13090 TIMESTAMP not DATE
# 12th Apr 2011  eweb     #00008 TIMESTAMP, IDs are NUMBER(19)
# 14th Apr 2011  eweb     #00008 IDs are NUMBER(19)
# 26th May 2011  eweb     #00009 INTEGER not NUMBER(1), NUMERIC(19) not INTEGER
# 26th May 2011  eweb     #13200 NUMERIC(19)
#  9th Jun 2011  eweb     #00009 Property names
#

# TODO #12012 Initialize Extra_hist tables
# TODO #12012 Update latest new columns in Extra_hist tables
use strict;

use XML::Simple;
use Data::Dumper;
use Getopt::Std;

my %opts = ( d => undef(),
             m => undef(),
             n => undef(),
             p => undef(),
             b => undef(),
             v => undef(),
             w => undef(),
             o => undef(),
             y => undef(),
           );

if ( !getopts("d:m:n:p:b:v:w:o:y:", \%opts) or @ARGV > 1 ) {
  print STDERR "Unknown arg $ARGV[0]\n" if @ARGV > 0;
  Usage();
  exit;
}

sub Usage() {
  print "Usage: $0 <options> path to extrainfo.xml\n";
  print " -d drive\n";
  print " -m major\n";
  print " -n minor\n";
  print " -p point\n";
  print " -b build\n";
  print " -v verbose\n";
  print " -w what (both|oracle|mssql|both)\n";
  print " -o output\n";
  print " -y year\n";

}

## TODO need full list of classes
my %ClassNames = (
  70 => "WGoal",
  125 => "WCountry",
  126 => "WState",
);

my $verbose = $opts{v};

my $what = $opts{w};

my $out = $opts{o};

$out = "gen" unless( $out );

my $Year = (localtime(time))[5] + 1900;

my $ExtraInfoXml = $ARGV[0];

$ExtraInfoXml = "Extra_Info.xml" unless ($ExtraInfoXml);

my $info = XMLin( $ExtraInfoXml, KeyAttr => {}, ForceArray => qr/option/);

#print Dumper($info);

my $Drive;
if ( defined( $opts{d} ) ) {
  $Drive = $opts{d};
}

if ( defined( $opts{y} ) ) {
  $Year = $opts{y};
}

my ($Major, $Minor, $Point, $Build, $Custom) = GetBuildNumber($Drive);

if ( defined( $opts{m} ) ) {
  $Major = $opts{m};
}
if ( defined( $opts{n} ) ) {
  $Minor = $opts{n};
}
if ( defined( $opts{p} ) ) {
  $Point = $opts{p};
}
if ( defined( $opts{b} ) ) {
  $Build = sprintf( "%03d", $opts{b} );
}
my $mnpb = "$Major.$Minor.$Point.$Build";

my $dbms;

my $dos = $^O eq "MSWin32";
sub osify($) {
  my ($path) = @_;
  if ( $dos ) {
    $path =~ s!/!\\!g;
  }
  else {
    $path =~ s!\\!/!g;
  }
  return $path;
}

sub propertyCase($) {
  my ($prop) = @_;
  #return lcfirst $prop;
  return ucfirst $prop;
}

sub GetBuildNumber($) {
  print "GetBuildNumber(@_)\n" if ( $verbose );
  my ($Major, $Minor, $Point, $Build, $Custom);

  my ($drive) = @_;

  my $BuildNoFile = "$drive/topclass/oracle/topclass/sources/buildno.h";
  if ( ! -e $BuildNoFile ) {
    my $VersionInfoFile = "$drive/topclass/oracle/topclass/sources/versioninfo.h";
    if ( -e $VersionInfoFile ) {
      $BuildNoFile = $VersionInfoFile;
    }
    else {
      my $NeoBuildNoFile = "$drive/topclass/neo/sources/buildno.h";
      if ( -e $NeoBuildNoFile ) {
        $BuildNoFile = $NeoBuildNoFile;
      }
      else {
        my $VersionInfoFile = "$drive/topclass/neo/sources/versioninfo.h";
        if ( -e $VersionInfoFile ) {
          $BuildNoFile = $VersionInfoFile;
        }
      }
    }
  }

  $BuildNoFile = osify($BuildNoFile);
  print "$BuildNoFile\n" if ( $verbose );

  if ( !open( BUILDNO, $BuildNoFile ) ) {
    print "**** Cannot open file $BuildNoFile for reading\n";
    return;
  }

  while ( <BUILDNO> ) {
    if ( /\#define BUILDNUMBER +([0-9]+)/ ) {
      $Build = $1;
    }
    elsif ( /\#define MAJORREVISION +([0-9]+)/ ) {
      $Major = $1;
    }
    elsif ( /\#define MINORREVISION +([0-9]+)/ ) {
      $Minor = $1;
    }
    elsif ( /\#define POINTREVISION +([0-9]+)/ ) {
      $Point = $1;
    }
    elsif ( /\#define BUILDINFO _TEXT\(\"(.*)\"\)/ ) {
      $Custom = $1;
    }
    elsif ( /\#define BUILDINFO \"(.*)\"/ ) {
      $Custom = $1;
    }
  }
  close BUILDNO;

  $Build = sprintf("%03d", $Build);
  return ($Major, $Minor, $Point, $Build, $Custom);
}

sub gen_banner($) {
  my $file = shift;
  print SQL "--\n";
  print SQL "-- File: $file\n";
  print SQL "-- Author: eweb\n";
  print SQL "-- This file was generated by a Perl program.\n";
  print SQL "-- Copyright WBT Systems, 1995-$Year\n";
  print SQL "--\n";
  if ( $dbms eq "oracle" ) {
    print SQL "COLUMN DUMMY_TITLE NOPRINT\n";
    print SQL "TTITLE LEFT COL 3 '-- ============================================================ --' SKIP 1 -\n";
    printf SQL "       LEFT COL 3 '-- File: %-54s --' SKIP 1 -\n", $file;
    print SQL "       LEFT COL 3 '-- ============================================================ --' SKIP 2\n";
    print SQL "SELECT NULL AS DUMMY_TITLE\n";
    print SQL "FROM DUAL\n";
    print SQL "/\n";
    print SQL "TTITLE OFF\n";
    print SQL "\n";
  }
  else {
    print SQL "PRINT '============================';\n";
    print SQL "PRINT 'File: $file';\n";
    print SQL "PRINT '============================';\n";
    print SQL "PRINT '';\n";
    print SQL "PRINT '-- ------------------------------------------------------------------------------';\n";
    print SQL "GO\n";
    #print SQL "\n";
  }
}

sub gen_footer($) {
  my $file = shift;
  $file =~ s!_[sb]\.sql!!;
  $file =~ s!\.sql!!;
  if ( $file eq "extratrigs" ) {
    $file = "EXTRA-TRIGGERS";
  }
  if ( $dbms eq "oracle" ) {
    print SQL "BEGIN\n";
    print SQL "  updateConfig('$file', '$mnpb');\n";
    print SQL "END;\n";
    print SQL "/\n";
  }
  else {
    print SQL "BEGIN\n";
    print SQL "  EXECUTE updateConfig N'$file', N'$mnpb';\n";
    print SQL "END\n";
    print SQL "GO\n";
  }
}

sub gen_extrainfo_lsp($;$) {

  $_ = shift;
  my $table = shift;

  #my $var0 = %{$_}->{name};
  #my $var1 = ${$_}{name};

  #print "var0: $var0\n";
  #print "var1: $var1\n";

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    my $objClass = $1;
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );
    print SQL "(make-cclass :name \"$table\" :audit-action t :audit-versions '(40)\n";
    print SQL "      :slots (list\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $size = ${$_}{Size};
      my $type = ${$_}{Type};
      my $default = ${$_}{Default};
      my $nullable = ${$_}{Nullable};
      my $otherClassID = ${$_}{ObjClassID};
      $default = "$default";
      if ( $default =~ /HASH\(0x.+\)/ ) {
        $default = "";
      }
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
        $default = ${$_}{value}->{default};
        $nullable = ${$_}{value}->{nullable};
        $otherClassID = ${$_}{value}->{objClassID};
        $default = "$default";
        if ( $default =~ /HASH\(0x.+\)/ ) {
          $default = "";
        }
      }
      #print "name: $name type: $type size: $size default: $default\n";
      #my ($sqlname, $sqltype, $sqldef, $sqlnull);

      my $sqlnull;
      my $lsptype;
      if ( $type eq 1 ) {
        $lsptype = ":CNeoString";
      }
      elsif ( $type eq 2 ) {
        $lsptype = ":Long";
      }
      elsif ( $type eq 3 ) {
        $lsptype = ":ETcDateTime";
      }
      elsif ( $type eq 5 ) {
        $lsptype = ":ENeoString";
      }
      elsif ( $type eq 6 ) {
        $lsptype = ":ENeoXDBSwizzler";
        $name =~ s!_ID$!!;
      }
      elsif ( $type eq 7 ) {
        $lsptype = ":Long";
      }
      elsif ( $type eq 8 ) {
        $lsptype = ":Long";
      }
      printf SQL "      (make-slot :name %-14s :type %s", "\"${name}\"", $lsptype;
      if ( $size ) {
        print SQL " :size $size";
      }
      if ( $type eq 6 and $otherClassID ) {
        print SQL " :othertype \"$ClassNames{$otherClassID}\"";
      }
      if ( $type eq 5 or $type eq 6 ) {
        print SQL " :embed t";
      }
      if ( $type eq 7 ) {
        print SQL " :decimal t";
      }
      if ( $type eq 8 ) {
        print SQL " :boolean t";
      }
      if ( $default ne undef ) {
        print SQL " :init $default";
      }
      print SQL ")\n";
    }
    print SQL "))\n";
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub dateType() {
  if ( $dbms eq "oracle" ) {
    if ( $Major ge 9 ) {
      return "TIMESTAMP";
    }
    return "DATE";
  }
  else {
    return "DATETIME";
  }
}
sub gen_core_extra_fields($;$) {

  $_ = shift;
  my $table = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    my $objClass = $1;
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );
    print SQL "--================================================================================\n";
    print SQL "-- TABLE $table:\n";
    print SQL "--================================================================================\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $size = ${$_}{Size};
      my $type = ${$_}{Type};
      my $default = ${$_}{Default};
      my $nullable = ${$_}{Nullable};
      $default = "$default";
      if ( $default =~ /HASH\(0x.+\)/ ) {
        $default = "";
      }
      else {
        #print "name: $name default: ". keys ( %{$default} ) ."\n";
        #print "name: $name default: $default\n";
      }
      #print "name: $name type: $type size: $size default: $default\n";
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
        $default = ${$_}{value}->{default};
        $nullable = ${$_}{value}->{nullable};
        $default = "$default";
        if ( $default =~ /HASH\(0x.+\)/ ) {
          $default = "";
        }
      }
      print SQL "ALTER TABLE $table ADD\n";
      print SQL "(\n" if ( $dbms eq "oracle" );

      #my ($sqlname, $sqltype, $sqldef, $sqlnull);

      my $sqlnull;
      my $sqltype;
      if ( $type eq 1 ) {
        unless ( $size ) {
          $size = 255 if ( $dbms eq "oracle" );
          $size = 254 if ( $dbms eq "mssql" );
        }
        unless ( $default ) {
          $default = "''" if ( $dbms eq "oracle" );
          $default = "N''" if ( $dbms eq "mssql" );
        }

        if ( $dbms eq "oracle" ) {
          $sqlnull = " NULL" ;
        }
        else {
          $sqlnull = "";
        }
        if ( $dbms eq "oracle" ) {
          $sqltype = "VARCHAR2" ;
        }
        else {
          $sqltype = "NVARCHAR";
        }
        #print SQL "  W${name}               VARCHAR2($size)         DEFAULT $default NULL\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  "$sqltype($size)", "DEFAULT $default", $sqlnull;
      }
      elsif ( $type eq 2 ) {
        $size = 10 unless ( $size );
        if ( $nullable ) {
          #$default = 0 unless ( $default );
          #print SQL "  W${name}               NUMBER($size)         NULL\n";
          printf SQL "  %-21s %-21s%s%s\n", "W${name}",  ($dbms eq "oracle" ? "NUMBER($size)" : "INTEGER"), "NULL";
        }
        else {
          $default = 0 unless ( $default );
          #print SQL "  W${name}               NUMBER($size)         DEFAULT $default NOT NULL\n";
          printf SQL "  %-21s %-21s%s%s\n", "W${name}",  ($dbms eq "oracle" ? "NUMBER($size)" : "INTEGER"), "DEFAULT $default ", "NOT NULL";
        }
      }
      elsif ( $type eq 3 ) {
        #print SQL "  W${name}               DATE         NULL\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  dateType(), "NULL";
      }
      elsif ( $type eq 5 ) {
        #print SQL "  W${name}               CLOB         DEFAULT EMPTY_CLOB()\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  ($dbms eq "oracle" ? "CLOB" : "NTEXT"), ($dbms eq "oracle" ? "DEFAULT EMPTY_CLOB()" : "DEFAULT N''");
      }
      elsif ( $type eq 6 ) {
        if ( $Major ge 9 ) {
          $size = 19 unless ( $size );
        }
        else {
          $size = 10 unless ( $size );
        }
        #print SQL "  W${name}               NUMBER($size)         NULL\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  ($dbms eq "oracle" ? "NUMBER($size)" : ($Major ge 9 ? "NUMERIC($size)" : "INTEGER")), "", "NULL";
      }
      elsif ( $type eq 7 ) {
        #$size = 10 unless ( $size );
        #print SQL "  W${name}               DECIMAL(9,2)         DEFAULT 0 NOT NULL\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  "DECIMAL(9,2)", "DEFAULT 0 ", "NOT NULL";
      }
      elsif ( $type eq 8 ) {
        $default = 0 unless ( $default );
        $size = 1 unless ( $size );
        #print SQL "  W${name}               NUMBER($size)            DEFAULT 0 NOT NULL\n";
        printf SQL "  %-21s %-21s%s%s\n", "W${name}",  ($dbms eq "oracle" ? "NUMBER($size)" : "INTEGER"), "DEFAULT $default ", "NOT NULL";
      }

      if ( $type eq 5 and $dbms eq "oracle" ) {
        print SQL ") LOB( W${name} ) STORE AS ( TABLESPACE &tclobs )\n";
      }
      else {
        print SQL ")\n" if ( $dbms eq "oracle" );
      }
      print SQL "/\n" if ( $dbms eq "oracle" );
      print SQL "GO\n" if ( $dbms eq "mssql" );
    }
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_core_extra_init($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );
    print SQL "--================================================================================\n";
    print SQL "-- Initialize $table\n";
    print SQL "--================================================================================\n";

    print SQL "INSERT INTO $table( W${objClass}_ID )\n";
    print SQL "  SELECT W${objClass}_ID\n";
    print SQL "  FROM W${objClass} a\n";
    print SQL "  WHERE NOT EXISTS( SELECT NULL\n";
    print SQL "                    FROM $table b\n";
    print SQL "                    WHERE a.W${objClass}_ID = b.W${objClass}_ID)\n";
    if ( $dbms eq "oracle" ) {
      print SQL "/\n";
      print SQL "COMMIT\n";
      print SQL "/\n";
      print SQL "EXECUTE dbms_stats.gather_table_stats( null, '$table' );\n";
    }
    else {
      print SQL "GO\n";
    }
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_core_extra_triggs($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );
    my $trig  = $table;
    my $base = $objClass;
    $base = "ULM" if ( $objClass eq "Page" );
    $base = "ULM" if ( $objClass eq "Course" );
    $base = "ULM" if ( $objClass eq "Exercise" );
    $base = "Question" if ( $objClass eq "DllQuestion" );
    $base = "Answer" if ( $objClass eq "DllAnswer" );
    $base = "Action" if ( $objClass =~ /Action$/ );

    $base = "OfferingPart" if ( $objClass eq "OfferedClass" );
    $base = "OfferingPart" if ( $objClass eq "OfferedEvent" );
    $base = "OfferingPart" if ( $objClass eq "OfferedResource" );

    if ( $objClass eq "RegistrationRequest_UExtra" or $table eq "WRegistrationRequest_UExtra" ) {
      $table = "WRegistrationRequest_UExtra";
      $trig = "WRegistrationRequest_UExtra";
      $objClass = "RegistrationRequest";
      $base = "RegistrationRequest";
    }
    else {
      $table = "W${base}_Extra";
    }

    #print SQL "--================================================================================\n";
    #print SQL "-- TABLE $table:\n";
    #print SQL "--================================================================================\n";

    if ( $dbms eq "oracle" ) {
      print SQL "CREATE OR REPLACE TRIGGER i$trig\n";
      print SQL "AFTER INSERT OR DELETE ON W${objClass}\n";
      print SQL "FOR EACH ROW\n";
      print SQL "BEGIN\n";
      print SQL "  IF ( INSERTING ) THEN\n";
      print SQL "    INSERT INTO $table (W${base}_ID) VALUES (:new.W${objClass}_ID);\n";
      print SQL "  END IF;\n";
      print SQL "  IF ( DELETING ) THEN\n";
      print SQL "    DELETE FROM $table WHERE W${base}_ID  = :old.W${objClass}_ID;\n";
      print SQL "  END IF;\n";
      print SQL "END;\n";
      print SQL "/\n";
      print SQL "SHOW ERRORS\n";
      print SQL "\n";
    }
    else {
      print SQL "\n";
      print SQL "--================================================================================\n";
      print SQL "-- Trigger: i$trig\n";
      print SQL "--================================================================================\n";
      print SQL "IF EXISTS\n";
      print SQL " (SELECT NULL FROM sysobjects\n";
      print SQL "  WHERE name = 'i$trig' AND Type = 'TR' )\n";
      print SQL "BEGIN\n";
      print SQL "  DROP TRIGGER i$trig;\n";
      print SQL "  PRINT 'INSTALL --> TRIGGER i$trig dropped';\n";
      print SQL "END\n";
      print SQL "GO\n";
      print SQL "CREATE TRIGGER i$trig\n";
      print SQL "ON W${objClass}\n";
      print SQL "  AFTER INSERT, DELETE\n";
      print SQL "AS\n";
      print SQL "BEGIN\n";
      print SQL "  INSERT INTO $table (W${base}_ID)\n";
      print SQL "  SELECT W${objClass}_ID FROM Inserted;\n";
      print SQL "  DELETE FROM $table WHERE W${base}_ID IN\n";
      print SQL "  (SELECT W${objClass}_ID FROM Deleted);\n";
      print SQL "END;\n";
      print SQL "\n";
      print SQL "GO\n";
      print SQL "IF( \@\@ERROR <> 0 ) BEGIN\n";
      print SQL "  PRINT      'ERROR!  --> Failed to create TRIGGER i$trig';\n";
      print SQL "  RAISERROR ('ERROR!  --> Failed to create TRIGGER i$trig', 16, 127);\n";
      print SQL "END ELSE\n";
      print SQL "  PRINT 'INSTALL --> TRIGGER i$trig created';\n";
      print SQL "GO\n";
      print SQL "\n";
    }
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub UPDATE($) {
  my $x = shift;
  return "UPDATE($x)";
}
sub gen_tc_audit_trigs_extra($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );
    #print SQL "--================================================================================\n";
    #print SQL "-- TABLE $table:\n";
    #print SQL "--================================================================================\n";

    my @fields;
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      @fields = (@fields, $name) unless ( $type eq 5 );
    }

    if ( $#fields eq -1 ) {
      return;
    }
    my $trig = $table;
    if ( $dbms eq "oracle" ) {
      $trig = "WRepLiveEvent_Extra" if ( $trig eq "WRepeatableLiveEvent_Extra" );
      $trig = "WRegRequest_UExtra" if ( $trig eq "WRegistrationRequest_UExtra" );
    }
    if ( $dbms eq "mssql" ) {
      print SQL "\n";
      print SQL "\n";
      print SQL "--================================================================================\n";
      print SQL "-- Trigger: aud_$trig\n";
      print SQL "--================================================================================\n";
      print SQL "IF EXISTS\n";
      print SQL " (SELECT NULL FROM sysobjects\n";
      print SQL "  WHERE name = 'aud_${table}' AND Type = 'TR' )\n";
      print SQL "BEGIN\n";
      print SQL "  DROP TRIGGER aud_$trig;\n";
      print SQL "  PRINT 'INSTALL --> TRIGGER aud_$trig dropped';\n";
      print SQL "END\n";
      print SQL "GO\n";
    }

    if ( $dbms eq "mssql" ) {
      print SQL "CREATE TRIGGER aud_$trig ON $table\n";
      print SQL "FOR INSERT, UPDATE, DELETE\n";
      print SQL "AS\n";
      print SQL "  IF ";
      print SQL join( "\n  OR ", map( ( "UPDATE(W$_)" ), @fields ) );
      print SQL "\n";
    }
    else {
      print SQL "CREATE OR REPLACE TRIGGER aud_$trig\n";
      print SQL "BEFORE INSERT OR\n";
      print SQL "       UPDATE OF W";
      print SQL join( ", W", @fields );
      print SQL " OR\n";
      print SQL "       DELETE\n";
      print SQL "ON     $table\n";
      print SQL "FOR EACH ROW\n";
    }
    print SQL "DECLARE\n";
    print SQL "\n";
    if ( $dbms eq "mssql" ) {
      my $fmt = "  \@%-26s %s\n";
      printf SQL $fmt, "lAuditedAction", "NCHAR(1)";
      $fmt = " ,\@%-26s %s\n";
      printf SQL $fmt, "lAction", "INTEGER";
      printf SQL $fmt, "lICount", "INTEGER";
      printf SQL $fmt, "lDCount", "INTEGER";
      printf SQL $fmt, "l${objClass}_ID", "INTEGER";
      foreach ( @{${$_}{option}} ) {
        my $name = ucfirst ${$_}{name};
        my $size = ${$_}{Size};
        my $type = ${$_}{Type};
        if ( ${$_}{value} ) {
          $size = ${$_}{value}->{size};
          $type = ${$_}{value}->{type};
        }
        $name =~ s!_id$!_ID!i;
        if ( $type eq 1 ) {
          $size = 254 unless ( $size );
          printf SQL $fmt, "l${name}", "NVARCHAR($size)";
        }
        elsif ( $type eq 2 or $type eq 6 or $type eq 8 ) {
          printf SQL $fmt, "l${name}", "INTEGER";
        }
        elsif ( $type eq 3 ) {
          printf SQL $fmt, "l${name}", "DATETIME";
        }
        elsif ( $type eq 7 ) {
          printf SQL $fmt, "l${name}", "DECIMAL(9,2)";
        }
      }
      $fmt = " ,\@%-26s %s;\n";
      printf SQL $fmt, "cRowCur", "CURSOR";
      print SQL "\n";
    }
    else {
      print SQL "  lAuditedAction  CHAR(1);\n";
      foreach ( @{${$_}{option}} ) {
        my $type = ${$_}{Type};
        if ( ${$_}{value} ) {
          $type = ${$_}{value}->{type};
        }
        if ( $type eq 3 ) {
          print SQL "  lServerDate " . dateType() . " := Wbt_GetServerDate();\n";
          last;
        }
      }
    }
    print SQL "BEGIN\n";
    if ( $dbms eq "mssql" ) {
      print SQL "\n";
      print SQL "  SELECT \@lICount = COUNT(*) FROM INSERTED;\n";
      print SQL "  SELECT \@lDCount = COUNT(*) FROM DELETED;\n";
      print SQL "\n";
      print SQL "  SET    \@lAction = SIGN(\@lICount - \@lDCount);\n";
      print SQL "\n";
      print SQL "  IF( \@lAction = 1 )\n";
      print SQL "  BEGIN\n";
      print SQL "    SET \@lAuditedAction = N'I';\n";
      print SQL "    SET \@cRowCur = CURSOR READ_ONLY FOR\n";
      print SQL "    SELECT\n";
      print SQL "      i.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,i.W$_\n";
      }
      print SQL "    FROM INSERTED i;\n";
      print SQL "  END\n";
      print SQL "  ELSE IF( \@lAction = 0 )\n";
      print SQL "  BEGIN\n";
      print SQL "    SET \@lAuditedAction = N'U';\n";
      print SQL "    SET \@cRowCur = CURSOR READ_ONLY FOR\n";
      print SQL "    SELECT\n";
      print SQL "      i.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,i.W$_\n";
      }
      print SQL "    FROM INSERTED AS i\n";
      print SQL "    JOIN DELETED AS d\n";
      print SQL "    ON ( d.W${objClass}_ID = i.W${objClass}_ID )\n";
      print SQL "    WHERE";
    }
    else {
      print SQL "  IF (INSERTING) THEN\n";
      print SQL "\n";
      print SQL "    lAuditedAction := 'I';\n";
      print SQL "\n";
      print SQL "    oAuditExtra.aud_$trig\n";
      print SQL "    (\n";
      print SQL "      lAuditedAction\n";
      print SQL "     ,:new.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,:new.W$_\n";
      }
      print SQL "    );\n";
      print SQL "\n";
      print SQL "  ELSIF\n";
      print SQL "    (\n";
      print SQL "      UPDATING\n";
      print SQL "      AND\n";
      print SQL "      (";
    }
    my $first = 1;
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 1 ) {
        if ( $first ) {
          $first = undef;
          print SQL "\n           ";
        }
        else {
          print SQL "\n        OR ";
        }
        if ( $dbms eq "oracle" ) { print SQL "NVL(:new.W$name, '''') <> NVL(:old.W$name, '''')" }
        else { print SQL "ISNULL(i.W$name, 'N''') <> ISNULL(d.W$name, 'N''')" }
      }
      elsif ( $type eq 2 or $type eq 8 ) {
        if ( $first ) {
          $first = undef;
          print SQL "\n           ";
        }
        else {
          print SQL "\n        OR ";
        }
        if ( $dbms eq "oracle" ) { print SQL ":new.W$name <> :old.W$name" }
        else { print SQL "i.W$name <> d.W$name" }
      }
      elsif ( $type eq 3 ) {
        if ( $first ) {
          $first = undef;
          print SQL "\n           ";
        }
        else {
          print SQL "\n        OR ";
        }
        if ( $dbms eq "oracle" ) { print SQL "NVL(:new.W$name, lServerDate) <> NVL(:old.W$name, lServerDate)" }
        else { print SQL "ISNULL(i.W$name, dbo.wbt_GetServerDate()) <> ISNULL(d.W$name, dbo.wbt_GetServerDate())" }
      }
      elsif ( $type eq 6 ) {
        if ( $first ) {
          $first = undef;
          print SQL "\n           ";
        }
        else {
          print SQL "\n        OR ";
        }
        if ( $dbms eq "oracle" ) { print SQL "NVL(:new.W$name, 0) <> NVL(:old.W$name, 0)" }
        else { print SQL "ISNULL(i.W$name, 0) <> ISNULL(d.W$name, 0)" }
        #print SQL ":new.W$name <> :old.W$name"
      }
      elsif ( $type eq 7 ) {
        if ( $first ) {
          $first = undef;
          print SQL "\n           ";
        }
        else {
          print SQL "\n        OR ";
        }
        if ( $dbms eq "oracle" ) { print SQL ":new.W$name <> :old.W$name" }
        else { print SQL "i.W$name <> d.W$name" }
      }
    }

    if ( $dbms eq "mssql" ) {
      print SQL ";\n";
      print SQL "  END\n";
      print SQL "  ELSE IF( \@lAction = -1 )\n";
      print SQL "  BEGIN\n";
      print SQL "    SET \@lAuditedAction = N'D';\n";
      print SQL "    SET \@cRowCur = CURSOR READ_ONLY FOR\n";
      print SQL "    SELECT\n";
      print SQL "      d.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,d.W$_\n";
      }
      print SQL "    FROM DELETED d;\n";
      print SQL "  END\n";
      print SQL "  --> Iterating...\n";
      print SQL "  OPEN  \@cRowCur;\n";
      print SQL "  FETCH NEXT FROM \@cRowCur\n";
      print SQL "    INTO\n";
      print SQL "  \@l${objClass}_ID\n";
      print SQL " ,";
      print SQL join( "\n ,", map( ( "\@l$_" ), @fields ) );
      print SQL ";\n";
      print SQL "  WHILE( \@\@FETCH_STATUS = 0 )\n";
      print SQL "  BEGIN\n";
      print SQL "\n";
      print SQL "    EXECUTE oAuditExtra_aud_$trig \@lAuditedAction, \@l${objClass}_ID";
      foreach ( @fields ) {
        print SQL ", \@l$_";
      }
#      , @lPrefix_ID, @lSuffix_ID, @lJobTitle, @lPhone1, @lPhone2, @lFaxNumber, @lAddress1, @lAddress2, @lCity, @lState_ID, @lZip, @lCountry_ID, @lApplyTax, @lMember, @lMemberStartDate, @lMemberEndDate
      print SQL ";\n";
      print SQL "    FETCH NEXT\n";
      print SQL "    FROM \@cRowCur\n";
      print SQL "    INTO\n";
      print SQL "  \@l${objClass}_ID\n";
      print SQL " ,";
      print SQL join( "\n ,", map( ( "\@l$_" ), @fields ) );
      print SQL ";\n";
      print SQL "\n";
      print SQL "  END -->WHILE<--\n";
      print SQL "\n";
      print SQL "  CLOSE       \@cRowCur;\n";
      print SQL "  DEALLOCATE  \@cRowCur;\n";
      print SQL "END -->aud_$trig<--\n";
      print SQL "GO\n";
      print SQL "IF( \@\@ERROR <> 0 ) BEGIN\n";
      print SQL "  PRINT      'ERROR!  --> Failed to create TRIGGER aud_$trig';\n";
      print SQL "  RAISERROR ('ERROR!  --> Failed to create TRIGGER aud_$trig', 16, 127);\n";
      print SQL "END ELSE\n";
      print SQL "  PRINT 'INSTALL --> TRIGGER aud_$trig created';\n";
      print SQL "GO\n";
    }
    else {
      print SQL "\n      )\n";
      print SQL "    )\n";
      print SQL "  THEN\n";
      print SQL "\n";
      print SQL "    lAuditedAction := 'U';\n";
      print SQL "\n";
      print SQL "    oAuditExtra.aud_$trig\n";
      print SQL "    (\n";
      print SQL "      lAuditedAction\n";
      print SQL "     ,:new.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,:new.W$_\n";
      }
      print SQL "    );\n";
      print SQL "\n";
      print SQL "  ELSIF (DELETING) THEN\n";
      print SQL "\n";
      print SQL "    lAuditedAction := 'D';\n";
      print SQL "\n";
      print SQL "    oAuditExtra.aud_$trig\n";
      print SQL "    (\n";
      print SQL "      lAuditedAction\n";
      print SQL "     ,:old.W${objClass}_ID\n";
      foreach ( @fields ) {
        print SQL "     ,:old.W$_\n";
      }
      print SQL "    );\n";
      print SQL "\n";
      print SQL "  END IF;\n";
      print SQL "\n";
      print SQL "END;\n";
      print SQL "/\n";
      print SQL "SHOW ERRORS\n";
      print SQL "\n";
      print SQL "\n";
    }
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_tc_audit_tables_extra($;$$) {

  $_ = shift;
  my $t = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    my $table = "W${objClass}_Extra_hist";

    if ( $dbms eq "oracle" ) {
      $table = "WRepLiveEvent_Extra_hist" if ( $table eq "WRepeatableLiveEvent_Extra_hist" );
      $table = "WRegRequest_Extra_hist" if ( $table eq "WRegistrationRequest_Extra_hist" );
      $table = "WRegRequest_UExtra_hist" if ( $t eq "WRegistrationRequest_UExtra" );
    }
    else {
      $table = "WRegistrationRequest_UExtra_hist" if ( $t eq "WRegistrationRequest_UExtra" );
    }
    my $primaryKey = "PK_${table}";
    if ( $dbms eq "oracle" ) {
      $primaryKey = "PK_WUserAssignGoal_Extra_hist" if ( $primaryKey eq "PK_WUserAssignedGoal_Extra_hist" );
      $primaryKey = "PK_WNotifRule_Extra_hist"      if ( $primaryKey eq "PK_WNotificationRule_Extra_hist" );
      $primaryKey = "PK_WEnrollReq_Extra_hist"      if ( $primaryKey eq "PK_WEnrollRequirement_Extra_hist" );
      $primaryKey = "PK_WAccessControl_Extra_hist"  if ( $primaryKey eq "PK_WAccessControlEntry_Extra_hist" );
      $primaryKey = "PK_WCancelPolicy_Extra_hist"   if ( $primaryKey eq "PK_WCancellationPolicy_Extra_hist" );
      $primaryKey = "PK_WTransDetail_Extra_hist"    if ( $primaryKey eq "PK_WTransactionDetail_Extra_hist" );
      if ( length($primaryKey) gt 30 ) {
        print "ERROR: $primaryKey too long!\n";
      }
    }

    print SQL "\n";
    print SQL "\n";
    print SQL "--================================================================================\n";
    print SQL "-- Table: ${table}\n";
    print SQL "--================================================================================\n";

    if ( $dbms eq "mssql" ) {
      print SQL "IF NOT EXISTS\n";
      print SQL " (SELECT NULL FROM sysobjects\n";
      print SQL "  WHERE Name = '${table}' AND xType = 'U' )\n";
      print SQL "BEGIN\n";
      print SQL "\n";
    }
    my $id_size = ( $Major ge 9 ) ? 19 : 10;

    print SQL "CREATE TABLE ${table}\n";
    print SQL "(\n";
    printf SQL " %-28s%-32s%s\n", "WAuditSeq",       $dbms eq "oracle" ? "NUMBER($id_size)" : ($Major ge 9 ? "NUMERIC($id_size)" : "INTEGER"),  "NOT NULL";
    printf SQL " ,%-28s%-32s%s\n", "WAuditDateTime",  dateType(), "NOT NULL";
    printf SQL " ,%-28s%-32s%s\n", "WAuditedAction",  $dbms eq "oracle" ? "CHAR(1)"    : "NCHAR(1)", "NOT NULL";
    printf SQL " ,%-28s%-32s%s\n", "WAuditUser_ID",   $dbms eq "oracle" ? "NUMBER($id_size)" : ($Major ge 9 ? "NUMERIC($id_size)" : "INTEGER"),  "NOT NULL";
    printf SQL " ,%-28s%-32s%s\n", "W${objClass}_ID", $dbms eq "oracle" ? "NUMBER($id_size)" : ($Major ge 9 ? "NUMERIC($id_size)" : "INTEGER"),  "NOT NULL";

    if ( 0 ) {
    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $size = ${$_}{Size};
      my $type = ${$_}{Type};
      my $default = ${$_}{Default};
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
        $default = ${$_}{value}->{default};
      }
      $default = "$default";
      if ( $default =~ /HASH\(0x.+\)/ ) {
        $default = "";
      }
      else {
        #print "name: $name default: ". keys ( %{$default} ) ."\n";
        #print "name: $name default: $default\n";
      }
      #print "name: $name type: $type size: $size default: $default\n";
      if ( $type eq 1 ) {
        unless ( $size ) {
          $size = 255 if ( $dbms eq "oracle" );
          $size = 254 if ( $dbms eq "mssql" );
        }
        #$default = "''" unless ( $default );
        printf SQL " ,%-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "VARCHAR2($size)" : "NVARCHAR($size)", "NULL";
      }
      elsif ( $type eq 2 ) {
        $size = 10 unless ( $size );
        #$default = 0 unless ( $default );
        printf SQL " ,%-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER($size)" : "INTEGER", "NULL";
      }
      elsif ( $type eq 3 ) {
        printf SQL " ,%-28s%-32s%s\n", "W${name}", dateType(), "NULL";
      }
      elsif ( $type eq 5 ) {
        #print SQL "  ,W${name}               CLOB         DEFAULT EMPTY_CLOB()\n";
      }
      elsif ( $type eq 6 ) {
        if ( $Major ge 9 ) {
          $size = 19 unless ( $size );
        }
        else {
          $size = 10 unless ( $size );
        }
        printf SQL " ,%-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER($size)" : ($Major ge 9 ? "NUMERIC($size)" : "INTEGER"), "NULL";
      }
      elsif ( $type eq 7 ) {
        #$size = 10 unless ( $size );
        printf SQL " ,%-28s%-32s%s\n", "W${name}", "DECIMAL(9,2)", "NULL";
      }
      elsif ( $type eq 8 ) {
        $size = 1;
        printf SQL " ,%-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER($size)" : "INTEGER", "NULL";
      }

      if ( $type eq 5 ) {
        #print SQL ") LOB( W${name} ) STORE AS ( TABLESPACE &tclobs )\n";
      }
      else {
        #print SQL ")\n";
      }
      #print SQL "/\n";
    }
    }

    if ( $dbms eq "oracle" ) {
      print SQL ")\n";
      print SQL "TABLESPACE &tchist\n";
      print SQL "/\n";
      print SQL "\n";
      print SQL "ALTER TABLE ${table}\n";
      print SQL "ADD CONSTRAINT $primaryKey PRIMARY KEY ( W${objClass}_ID, WAuditSeq ) USING INDEX TABLESPACE &tchist_indx\n";
      print SQL "/\n";
    }
    else {
      print SQL " ,CONSTRAINT $primaryKey PRIMARY KEY( W${objClass}_ID, WAuditSeq )\n";
      print SQL ");\n";
      print SQL "  IF( \@\@ERROR <> 0 ) BEGIN\n";
      print SQL "    PRINT      'ERROR!  --> Failed to create TABLE ${table}';\n";
      print SQL "    RAISERROR ('ERROR!  --> Failed to create TABLE ${table}', 16, 127);\n";
      print SQL "  END ELSE\n";
      print SQL "    PRINT 'INSTALL --> TABLE ${table} created';\n";
      print SQL "END;\n";
      print SQL "GO\n";
    }
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_tc_audit_columns_extra($;$$) {

  $_ = shift;
  my $t = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    my $table = "W${objClass}_Extra_hist";

    if ( $dbms eq "oracle" ) {
      $table = "WRepLiveEvent_Extra_hist" if ( $table eq "WRepeatableLiveEvent_Extra_hist" );
      $table = "WRegRequest_Extra_hist" if ( $table eq "WRegistrationRequest_Extra_hist" );
      $table = "WRegRequest_UExtra_hist" if ( $t eq "WRegistrationRequest_UExtra" );
    }
    else {
      $table = "WRegistrationRequest_UExtra_hist" if ( $t eq "WRegistrationRequest_UExtra" );
    }

    print SQL "\n";
    print SQL "\n";
    print SQL "--================================================================================\n";
    print SQL "-- Table: ${table}\n";
    print SQL "--================================================================================\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $size = ${$_}{Size};
      my $type = ${$_}{Type};
      my $default = ${$_}{Default};
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
        $default = ${$_}{value}->{default};
      }
      $default = "$default";
      if ( $default =~ /HASH\(0x.+\)/ ) {
        $default = "";
      }
      else {
        #print "name: $name default: ". keys ( %{$default} ) ."\n";
        #print "name: $name default: $default\n";
      }
      #print "name: $name type: $type size: $size default: $default\n";
      if ( $type eq 1 ) {
        unless ( $size ) {
          $size = 255 if ( $dbms eq "oracle" );
          $size = 254 if ( $dbms eq "mssql" );
        }
        #$default = "''" unless ( $default );
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "VARCHAR2($size)" : "NVARCHAR($size)", "NULL";
      }
      elsif ( $type eq 2 ) {
        $size = 10 unless ( $size );
        #$default = 0 unless ( $default );
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER($size)" : "INTEGER", "NULL";
      }
      elsif ( $type eq 3 ) {
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", dateType(), "NULL";
      }
      elsif ( $type eq 5 ) {
        #print SQL "  ,W${name}               CLOB         DEFAULT EMPTY_CLOB()\n";
        next;
      }
      elsif ( $type eq 6 ) {
        if ( $Major ge 9 ) {
          $size = 19 unless ( $size );
        }
        else {
          $size = 10 unless ( $size );
        }
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER($size)" : ($Major ge 9 ? "NUMERIC($size)" : "INTEGER"), "NULL";
      }
      elsif ( $type eq 7 ) {
        #$size = 10 unless ( $size );
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", "DECIMAL(9,2)", "NULL";
      }
      elsif ( $type eq 8 ) {
        #$size = 10 unless ( $size );
        print SQL "ALTER TABLE ${table} ADD\n";
        printf SQL "  %-28s%-32s%s\n", "W${name}", $dbms eq "oracle" ? "NUMBER(1)" : "INTEGER", "NULL";
      }

      if ( $type eq 5 ) {
        #print SQL ") LOB( W${name} ) STORE AS ( TABLESPACE &tclobs )\n";
      }
      else {
        #print SQL ")\n";
      }
      #print SQL "/\n";
      if ( $dbms eq "oracle" ) {
        print SQL "/\n";
      }
      else {
        print SQL "GO\n";
      }
    }

  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_oauditextra_s($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );

    $table = "WRepLiveEvent_Extra" if ( $table eq "WRepeatableLiveEvent_Extra" );
    $table = "WRegRequest_UExtra" if ( $table eq "WRegistrationRequest_UExtra" );

    print SQL "  PROCEDURE aud_$table\n";
    print SQL "  (\n";
    print SQL "    aAuditedAction              IN CHAR\n";
    print SQL "     ,a${objClass}_ID IN NUMBER\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 1 ) {
        $type = "VARCHAR2";
      }
      elsif ( $type eq 2 ) {
        $type = "NUMBER";
      }
      elsif ( $type eq 3 ) {
        $type = dateType();
      }
      elsif ( $type eq 5 ) {
        #print SQL "    ,a${name}               CLOB         DEFAULT EMPTY_CLOB()\n";
        next;
      }
      elsif ( $type eq 6 ) {
        $type = "NUMBER";
      }
      elsif ( $type eq 7 ) {
        #$size = 10 unless ( $size );
        $type = "DECIMAL";
      }
      elsif ( $type eq 8 ) {
        #$size = 10 unless ( $size );
        $type = "NUMBER";
      }
      print SQL "     ,a${name} IN $type\n";
    }
    print SQL "  );\n";
    print SQL "\n";
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

###
sub gen_oauditextra_b($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );

    $table = "WRepLiveEvent_Extra" if ( $table eq "WRepeatableLiveEvent_Extra" );
    $table = "WRegRequest_UExtra" if ( $table eq "WRegistrationRequest_UExtra" );

    my $histtable = "${table}_hist";
    $histtable = "WRegRequest_Extra_hist" if ( $histtable eq "WRegistrationRequest_Extra_hist" );

    print SQL "  PROCEDURE aud_$table\n";
    print SQL "  (\n";
    print SQL "    aAuditedAction              IN CHAR\n";
    print SQL "     ,a${objClass}_ID IN NUMBER\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 1 ) {
        $type = "VARCHAR2";
      }
      elsif ( $type eq 2 ) {
        $type = "NUMBER";
      }
      elsif ( $type eq 3 ) {
        $type = dateType();
      }
      elsif ( $type eq 5 ) {
        next;
      }
      elsif ( $type eq 6 ) {
        $type = "NUMBER";
      }
      elsif ( $type eq 7 ) {
        $type = "DECIMAL";
      }
      elsif ( $type eq 8 ) {
        $type = "NUMBER";
      }
      print SQL "     ,a${name} IN $type\n";
    }
    print SQL "  )\n";
    print SQL "  IS\n";
    print SQL "    lAuditUser_ID NUMBER := -1;\n";
    print SQL "  BEGIN\n";
    print SQL "    lAuditUser_ID := GetConnectionUser;\n";
    print SQL "\n";
    print SQL "    INSERT INTO ${histtable}\n";
    print SQL "    (\n";
    print SQL "      WAuditSeq\n";
    print SQL "     ,WAuditDateTime\n";
    print SQL "     ,WAuditedAction\n";
    print SQL "     ,WAuditUser_ID\n";
    print SQL "     ,W${objClass}_ID\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 5 ) {
        next;
      }
      print SQL "     ,W${name}\n";
    }
    print SQL "    )\n";
    print SQL "    VALUES\n";
    print SQL "    (\n";
    print SQL "      Aud_Seq.nextval\n";
    print SQL "     ,Wbt_GetServerDate()\n";
    print SQL "     ,aAuditedAction\n";
    print SQL "     ,lAuditUser_ID\n";
    print SQL "     ,a${objClass}_ID\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 5 ) {
        next;
      }
      print SQL "     ,a${name}\n";
    }
    print SQL "    );\n";
    print SQL "\n";
    print SQL "  END;\n";
    print SQL "\n";
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

###
sub gen_audit_extra($;$$) {

  $_ = shift;
  my $table = shift;
  my $objClass = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    $objClass = $1 unless ( $objClass );
    #print ${$_}{name} . "\n";

    $table = "W${objClass}_Extra" unless ( $table );

    #$table = "WRepLiveEvent_Extra" if ( $table eq "WRepeatableLiveEvent_Extra" );
    #$table = "WRegRequest_UExtra" if ( $table eq "WRegistrationRequest_UExtra" );

    print SQL "\n";
    print SQL "\n";
    print SQL "--================================================================================\n";
    print SQL "-- Procedure: oAuditExtra_aud_${table}\n";
    print SQL "--================================================================================\n";

    print SQL "IF EXISTS\n";
    print SQL " (SELECT NULL FROM sysobjects\n";
    print SQL "  WHERE id = object_id('oAuditExtra_aud_${table}'))\n";
    print SQL "BEGIN\n";
    print SQL "  DROP PROCEDURE oAuditExtra_aud_${table};\n";
    print SQL "  PRINT 'INSTALL --> PROCEDURE oAuditExtra_aud_${table} dropped';\n";
    print SQL "END\n";
    print SQL "GO\n";

    print SQL "CREATE PROCEDURE oAuditExtra_aud_$table\n";
    print SQL "  (\n";
    print SQL "    \@aAuditedAction              NCHAR(1)\n";
    print SQL "     ,\@a${objClass}_ID INTEGER\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      my $size = ${$_}{Size};
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 1 ) {
        $size = 254 unless ( $size );
        $type = "NVARCHAR($size)";
      }
      elsif ( $type eq 2 ) {
        $type = "INTEGER";
      }
      elsif ( $type eq 3 ) {
        $type = "DATETIME";
      }
      elsif ( $type eq 5 ) {
        next;
      }
      elsif ( $type eq 6 ) {
        $type = "INTEGER";
      }
      elsif ( $type eq 7 ) {
        $type = "DECIMAL(9,2)";
      }
      elsif ( $type eq 8 ) {
        $type = "INTEGER";
      }
      print SQL "     ,\@a${name} $type\n";
    }
    print SQL "  )\n";

    print SQL "AS\n";
    print SQL "BEGIN DECLARE\n";
    print SQL "  \@lID INTEGER\n";
    print SQL " ,\@lAuditUser_ID INTEGER;\n";
    print SQL "  EXECUTE getUniqueAuditID \@lID OUTPUT;\n";
    print SQL "  SET \@lAuditUser_ID = dbo.GetConnectionUser();\n";

    #print SQL "\n";
    print SQL "    INSERT INTO ${table}_hist\n";
    print SQL "    (\n";
    print SQL "      WAuditSeq\n";
    print SQL "     ,WAuditDateTime\n";
    print SQL "     ,WAuditedAction\n";
    print SQL "     ,WAuditUser_ID\n";
    print SQL "     ,W${objClass}_ID\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 5 ) {
        next;
      }
      print SQL "     ,W${name}\n";
    }
    print SQL "    )\n";
    print SQL "    VALUES\n";
    print SQL "    (\n";
    print SQL "      \@lID\n";
    print SQL "     ,dbo.wbt_GetServerDate()\n";
    print SQL "     ,\@aAuditedAction\n";
    print SQL "     ,\@lAuditUser_ID\n";
    print SQL "     ,\@a${objClass}_ID\n";
    foreach ( @{${$_}{option}} ) {
      my $name = ucfirst ${$_}{name};
      $name =~ s!_id$!_ID!i;
      my $type = ${$_}{Type};
      if ( ${$_}{value} ) {
        $type = ${$_}{value}->{type};
      }
      if ( $type eq 5 ) {
        next;
      }
      print SQL "     ,\@a${name}\n";
    }
    print SQL "    );\n";
    print SQL "\n";
    print SQL "END -->oAuditExtra_aud_$table<--\n";
    print SQL "\n";
    print SQL "GO\n";

    print SQL "IF( \@\@ERROR <> 0 ) BEGIN\n";
    print SQL "  PRINT      'ERROR!  --> Failed to create PROCEDURE oAuditExtra_aud_$table';\n";
    print SQL "  RAISERROR ('ERROR!  --> Failed to create PROCEDURE oAuditExtra_aud_$table', 16, 127);\n";
    print SQL "END ELSE\n";
    print SQL "  PRINT 'INSTALL --> PROCEDURE oAuditExtra_aud_$table created';\n";
    print SQL "GO\n";
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_scripts($) {

  $dbms = shift;
  if ( $out ) {
    mkdir( $out );
    if ( $out !~ m!/$! ) {
      $out = "$out/";
    }
  }

  mkdir( $out . uc $dbms );

  mkdir( "$out$dbms/Core" ) if ( $dbms eq "mssql" );
  mkdir( "$out$dbms/Internal" ) if ( $dbms eq "mssql" );
  mkdir( "$out$dbms/Internal/Audit" ) if ( $dbms eq "mssql" );

  my $file;
  my $path;

  $file = "core_extra_fields.sql";

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Core/$file" if ( $dbms eq "mssql" );


  if ( open( SQL, ">$path" ) ) {
    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_core_extra_fields($_);
    }

    #print $userInfo . "\n";
    #print $userInfo->{name} . "\n";

    gen_core_extra_fields( $userInfo, "WRegistrationRequest_UExtra" );

    gen_footer($file);
    close( SQL );
  }

  $file = "core_extra_init.sql";

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Core/$file" if ( $dbms eq "mssql" );

  if ( open( SQL, ">$path" ) ) {

    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_core_extra_init($_);
    }

    gen_core_extra_init( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

    gen_footer($file);
    close( SQL );
  }

  $file = "core_extra_triggs.sql";

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Core/$file" if ( $dbms eq "mssql" );

  if ( open( SQL, ">$path" ) ) {

    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    print SQL "\n" if ( $dbms eq "mssql" );

    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_core_extra_triggs($_);
    }

    gen_core_extra_triggs( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

    gen_footer($file);
    close( SQL );
  }


  #W:\topclass\oracle\topclass\Scripts\ORACLE\tc_audit_trigs_extra.sql
  $file = "tc_audit_trigs_extra.sql";
  $file = "audit_triggs_extra.sql" if ( $dbms eq "mssql" );

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

  if ( open( SQL, ">$path" ) ) {

    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_tc_audit_trigs_extra($_);
    }

    gen_tc_audit_trigs_extra( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

    gen_footer($file);
    close( SQL );
  }

  #W:\topclass\oracle\topclass\Scripts\ORACLE\tc_audit_trigs_extra.sql
  $file = "tc_audit_tables_extra.sql";
  $file = "audit_tables_extra.sql" if ( $dbms eq "mssql" );

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

  if ( open( SQL, ">$path" ) ) {

    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_tc_audit_tables_extra($_);
    }

    gen_tc_audit_tables_extra( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

    gen_footer($file);
    close( SQL );
  }

  #W:\topclass\oracle\topclass\Scripts\ORACLE\tc_audit_trigs_extra.sql
  $file = "tc_audit_columns_extra.sql";
  $file = "audit_columns_extra.sql" if ( $dbms eq "mssql" );

  $path = "$out$dbms/$file";
  $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

  if ( open( SQL, ">$path" ) ) {

    print ";$path\n";
    gen_banner($file);

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_tc_audit_columns_extra($_);
    }

    gen_tc_audit_columns_extra( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

    gen_footer($file);
    close( SQL );
  }

  if ( $dbms eq "mssql" ) {
    $file = "audit_extra.sql";

    $path = "$out$dbms/$file";
    $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

    if ( open( SQL, ">$path" ) ) {

      print ";$path\n";
      gen_banner($file);

      #print SQL "CREATE OR REPLACE PACKAGE BODY oAuditExtra\n";
      #print SQL "AS\n";
      my $userInfo;
      foreach ( @{$info->{section}} ) {
        $userInfo = \%{$_} unless ( $userInfo );
        gen_audit_extra($_);
      }

      gen_audit_extra( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

      #print SQL "END oAuditExtra;\n";
      #print SQL "/\n";
      #print SQL "SHOW ERRORS\n";
      gen_footer("o$file");
      close( SQL );
    }
  }
  else {
    $file = "oauditextra_s.sql";

    $path = "$out$dbms/$file";
    $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

    if ( open( SQL, ">$path" ) ) {

      print ";$path\n";
      gen_banner($file);

      print SQL "CREATE OR REPLACE PACKAGE oAuditExtra\n";
      print SQL "AS\n";

      my $userInfo;
      foreach ( @{$info->{section}} ) {
        $userInfo = \%{$_} unless ( $userInfo );
        gen_oauditextra_s($_);
      }

      gen_oauditextra_s( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

      print SQL "END oAuditExtra;\n";
      print SQL "/\n";
      print SQL "SHOW ERRORS\n";
      #gen_footer($file);
      close( SQL );
    }

    $file = "oauditextra_b.sql";

    $path = "$out$dbms/$file";
    $path = "$out$dbms/Internal/Audit/$file" if ( $dbms eq "mssql" );

    if ( open( SQL, ">$path" ) ) {

      print ";$path\n";
      gen_banner($file);

      print SQL "CREATE OR REPLACE PACKAGE BODY oAuditExtra\n";
      print SQL "AS\n";
      print SQL "\n";
      my $userInfo;
      foreach ( @{$info->{section}} ) {
        $userInfo = \%{$_} unless ( $userInfo );
        gen_oauditextra_b($_);
      }

      gen_oauditextra_b( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

      print SQL "END oAuditExtra;\n";
      print SQL "/\n";
      print SQL "SHOW ERRORS\n";
      gen_footer($file);
      close( SQL );
    }
  }

  if ( 0 ) {
    $file = "extratrigs.sql";

    $path = "$out$dbms/$file";
    $path = "$out$dbms/Core/$file" if ( $dbms eq "mssql" );

    my @extraInfoClasses = qw/User Class Page Course Exercise UserPage Message Student Tutor Answer Submission DllQuestion ExternalRef CourseInfo MsgAction AddAction RemoveAction EnrollAction DllAction AwardAction QPool QSelection TimeRestriction AccessControlEntry ContentData Group Operation Goal SubGoal AssignedGoal AttainedGoal OfferedGoal Category Offering OfferedClass OfferedEvent OfferedResource RepeatableLiveEvent Location LiveEvent ILTStudent EnrollRequest EnrollRequirement ApprovalRequest Manager RegistrationRequest RegistrationRequest_UExtra Partition Condition RollupRule RegulatoryBody NotificationRule UserAssignedGoal Signature SignedRecord Equipment Room Language InstructorUser ILTInstructor Comment RoomBooking NonAvailability CancellationPolicy PaymentToken Coupon Semester ShippingMethod Transaction TransactionDetail PaymentHistory OfferingUpSell Country State Account/;

    print "is $Major ge \"9\"?\n";
    if ( $Major ge "9" ) {
      print "$Major ge \"9\"\n" if ( $Major ge "9" );
      @extraInfoClasses = qw/User Class Page Course Exercise UserPage Message Student Tutor Answer Submission DllQuestion ExternalRef CourseInfo MsgAction AddAction RemoveAction EnrollAction DllAction AwardAction QPool QSelection TimeRestriction AccessControlEntry ContentData Group Operation Goal SubGoal AssignedGoal AttainedGoal OfferedGoal Category Offering OfferedClass OfferedEvent OfferedResource IltClass Location IltInstance IltStudent EnrollRequest EnrollRequirement ApprovalRequest Manager RegistrationRequest RegistrationRequest_UExtra Partition Condition RollupRule RegulatoryBody NotificationRule UserAssignedGoal Signature SignedRecord Equipment Room Language InstructorUser IltInstructor Comment RoomBooking NonAvailability CancellationPolicy PaymentToken Coupon Semester ShippingMethod Transaction TransactionDetail PaymentHistory OfferingUpSell Country State Account/;
    }

    if ( open( SQL, ">$path" ) ) {

      print ";$path\n";
      gen_banner($file);

      print SQL "\n" if ( $dbms eq "mssql" );
      my $userInfo;
      foreach ( @extraInfoClasses ) {
        #$userInfo = \%{$_} unless ( $userInfo );
        my %info = ( Name => $_ );
        $info{name} = "Extra${_}Fields";
        gen_core_extra_triggs(\%info);
      }

      #gen_core_extra_triggs( $userInfo, "WRegistrationRequest_UExtra", "RegistrationRequest" );

      gen_footer($file);
      close( SQL );
    }
  }
}

sub gen_lisp() {

  my $file;
  my $path;

  $file = "extrainfo.tmp";

  $path = "$file";

  if ( open( SQL, ">$path" ) ) {
    print ";$path\n";
    #gen_banner($file);
    #print SQL "(print (mapcar #'cclass-name *extrainfo-classes*))\n";
    print SQL "(setf *extrainfo-classes*\n";
    print SQL "  (list\n";

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_extrainfo_lsp($_);
    }

    #print $userInfo . "\n";
    #print $userInfo->{name} . "\n";

    gen_extrainfo_lsp( $userInfo, "WRegistrationRequest_UExtra" );

    #gen_footer($file);
    print SQL "))\n";
    #print SQL "(print (mapcar #'cclass-name *extrainfo-classes*))\n";
    close( SQL );
  }
}

sub gen_extrainfo_hbm($;$$) {
  $_ = shift;
  my $table = shift;
  my $entity = shift;

  if ( ${$_}{name} =~ /Extra(.+)Fields/ ) {
    my $objClass = $1;
    #print ${$_}{name} . "\n";

    $table = "W${objClass}Extra" unless ( $table );
    $entity = "W${objClass}ExtraInfo" unless ( $entity );
    my $file = "gen/java/topclass/topclass/domain/${entity}.hbm.xml";
    if ( !open( SQL, ">$file" ) ) {
      print "; Failed to open file $file $!\n";
      return;
    }
    print "; $file\n";
    print SQL "<?xml version=\"1.0\"?>\n";
    print SQL "<!--\n";
    print SQL "   File: ${entity}.hbm.xml\n";
    print SQL "   This file was generated by a perl program.\n";
    print SQL "   Copyright WBT Systems, 1995-$Year\n";
    print SQL "   Contents:\n";
    print SQL "-->\n";


    my $id = propertyCase( "Id" );

    print SQL "<!DOCTYPE hibernate-mapping PUBLIC\n";
    print SQL "     \"-//Hibernate/Hibernate Mapping DTD 3.0//EN\"\n";
    print SQL "     \"http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd\">\n";
    print SQL "<hibernate-mapping>\n";
    print SQL "  <class entity-name=\"${entity}\" table=\"W${objClass}_Extra\">\n";
    print SQL "    <id name=\"${id}\" type=\"long\" column=\"W${objClass}_ID\">\n";
    print SQL "      <generator class=\"foreign\">\n";
    print SQL "        <param name=\"property\">obj</param>\n";
    print SQL "      </generator>\n";
    print SQL "    </id>\n";
    print SQL "    <one-to-one name=\"obj\" class=\"com.wbtsystems.topclass.domain.W${objClass}\" constrained=\"true\" />\n";

    #print ${$_}{option} . "\n";
    foreach ( @{${$_}{option}} ) {
      my $name = propertyCase( ${$_}{name} );
      $name =~ s!_id$!_ID!i;
      my $size = ${$_}{Size};
      my $type = ${$_}{Type};
      my $default = ${$_}{Default};
      my $nullable = ${$_}{Nullable};
      my $otherClassID = ${$_}{ObjClassID};
      $default = "$default";
      if ( $default =~ /HASH\(0x.+\)/ ) {
        $default = "";
      }
      if ( ${$_}{value} ) {
        $size = ${$_}{value}->{size};
        $type = ${$_}{value}->{type};
        $default = ${$_}{value}->{default};
        $nullable = ${$_}{value}->{nullable};
        $otherClassID = ${$_}{value}->{objClassID};
        $default = "$default";
        if ( $default =~ /HASH\(0x.+\)/ ) {
          $default = "";
        }
      }
      #print "name: $name type: $type size: $size default: $default\n";
      #my ($sqlname, $sqltype, $sqldef, $sqlnull);

      my $sqlnull;
      my $lsptype;

      if ( $type eq 1 ) {
        $lsptype = "string";
      }
      elsif ( $type eq 2 ) {
        $lsptype = "integer";
      }
      elsif ( $type eq 3 ) {
        $lsptype = "com.wbtsystems.topclass.util.DateTimeType";
      }
      elsif ( $type eq 5 ) {
        $lsptype = "text";
      }
      elsif ( $type eq 6 ) {
        $lsptype = "long";
        $name =~ s!_ID$!_Id!;
      }
      elsif ( $type eq 7 ) {
        $lsptype = "big_decimal";
      }
      elsif ( $type eq 8 ) {
        $lsptype = "boolean";
      }
      if ( $type eq 2 ) {
        printf SQL "    <property name=\"%s\" type=\"%s\" insert=\"false\">\n", $name, $lsptype;
        printf SQL "      <column name=\"W%s\" default=\"%d\"/>\n", propertyCase($name), $default;
        printf SQL "    </property>";
      }
      else {
        printf SQL "    <property name=\"%s\" type=\"%s\" column=\"W%s\"", $name, $lsptype, propertyCase($name);
        if ( $type eq 3 ) {
          printf SQL " not-null=\"false\"";
        }
        elsif ( $type eq 7 ) {
          printf SQL " precision=\"10\"";
        }
        printf SQL " />";
      }
      if ( $size ) {
        #print SQL " :size $size";
      }
      if ( $type eq 6 and $otherClassID ) {
        #print SQL " :othertype \"$ClassNames{$otherClassID}\"";
      }
      if ( $type eq 5 or $type eq 6 ) {
        #print SQL " :embed t";
      }
      if ( $default ne undef ) {
        #print SQL " :init $default";
      }
      print SQL "\n";
    }
    print SQL "  </class>\n";
    print SQL "</hibernate-mapping>\n";
    close( SQL );
  }
  else {
    #print "Won't " . ${$_}{name} . "\n";
  }
}

sub gen_hbm() {

  my $file;
  my $path;

  #$file = "extrainfo.tmp";

  #$path = "$file";

  #if ( open( SQL, ">$path" ) ) {
  #  print ";$path\n";
  #  #gen_banner($file);
  #  print SQL "(setf *extrainfo-classes*\n";
  #  print SQL "  (list\n";

    my $userInfo;
    foreach ( @{$info->{section}} ) {
      $userInfo = \%{$_} unless ( $userInfo );
      gen_extrainfo_hbm($_);
    }

    #print $userInfo . "\n";
    #print $userInfo->{name} . "\n";

    gen_extrainfo_hbm( $userInfo, "WRegistrationRequest_UExtra", "WRegistrationRequestExtraUser" );

    #gen_footer($file);
  #  print SQL "))\n";
  #  close( SQL );
  #}
}

if ( $what eq "oracle" or $what eq "both" ) {
  gen_scripts("oracle");
}
if ( $what eq "mssql" or $what eq "both" ) {
  gen_scripts("mssql");
}

if ( $what eq "lisp" ) {
  gen_lisp();
}

if ( $what eq "hbm" ) {
  gen_hbm();
}

