#!/bin/sh

#
# File: get_lyrics
# Author: eamonn.webster@gmail.com
# Copyright eweb, 2026-2026
# Contents:
#
# Date:          Author:  Comments:
#
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit
exec "$script_dir/.venv/bin/python" "$script_dir/get_lyrics.py" "$@"
