#!/usr/bin/env ruby
#
# File: git-synch-all
# Author: eweb
# Copyright qstream, 2013-2015
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Synch all workspaces
# 24th Jun 2014  eweb     #0008 Discover workspaces
# 20th Aug 2014  eweb     #0008 Include branch qs-labs
# 20th Aug 2014  eweb     #0008 Call tag-releases
# 25th Mar 2015  eweb     #0008 Drop trove
#

tagged = nil

bin_dir = File.expand_path('../', __FILE__)
# puts bin_dir

Dir["#{ENV['HOME']}/projects/qstream/*"].each do |dir|
  next unless Dir.exist?(dir)
  Dir.chdir(dir) do |dir|
    next unless Dir.exist?('.git')
    remote = %x{git remote -v | grep -e 'origin.\\+fetch'}
    if remote =~ %r{git@github.com:qstream/(.+)\.git}
      repo = $1
      puts dir
      current = `git rev-parse --abbrev-ref HEAD`.chomp
      puts "current [#{current}]"
      puts remote

      system("git remote update")

      if repo == 'spaced-ed' && !tagged
        apps = %w{qs-alpha qs-bleedin qs-staging qs-labs}
        apps.each do |app|
          #tags = `#{bin_dir}/tag-releases.rb #{app}`.chomp
          tags = `tag-releases #{app}`.chomp
          puts tags unless tags.empty?
        end
        tagged = true
      end

      case repo
        when 'spaced-ed'
          branches = %w{master edge qs-labs}
        else
          branches = %w{master}
      end

      branches.each do |br|
        next if br == current
        system("git update-ref refs/heads/#{br} remotes/origin/#{br}")
      end

      system("git pull")
    end
  end
end
