#!/usr/bin/env ruby
#
# File: git-synch-all
# Author: eweb
# Copyright qstream, 2013-2015
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Synch all workspaces
# 24th Jun 2014  eweb     #0008 Discover workspaces
# 20th Aug 2014  eweb     #0008 Include branch qs-labs
# 20th Aug 2014  eweb     #0008 Call tag-releases
# 25th Mar 2015  eweb     #0008 Drop trove
# 26th May 2015  eweb     #0008 Clean up and colorize output
#  7th Sep 2015  eweb     #0008 bugfix branches
#

require 'open3'

tagged = nil

bin_dir = File.expand_path('../', __FILE__)
# puts bin_dir

Dir["#{ENV['HOME']}/projects/qstream/*"].each do |dir|
  next unless Dir.exist?(dir)
  Dir.chdir(dir) do |dir|
    next unless Dir.exist?('.git')
    remote = %x{git remote -v | grep -e 'origin.\\+fetch'}
    if remote =~ %r{git@github.com:qstream/(.+)\.git} ||
       remote =~ %r{https://github.com/qstream/(.+)\.git}
      remote = Regexp.last_match(0)
      repo = $1
      current = `git rev-parse --abbrev-ref HEAD`.chomp
      puts "\033[0;34m#{dir}\033[0m \033[0;35m#{current}\033[0m \033[0;36m#{remote}\033[0m"

      Open3.popen2e("git", "remote", "update") {|i,oe,t|
        oe.each {|line|
          line.chomp!
          if /Fetching repository, done./ =~ line
          elsif /Already up-to-date./ =~ line
          elsif /Fetching (.+)/ =~ line
            print "\033[2K\r#{line}"
          else
            puts line
          end
        }
      }
      print "\033[2K\r"

      if repo == 'spaced-ed' && !tagged
        apps = %w{qs-alpha qs-bleedin qs-staging qs-labs}
        apps.each do |app|
          #tags = `#{bin_dir}/tag-releases.rb #{app}`.chomp
          tags = `tag-releases #{app}`.chomp
          puts tags unless tags.empty?
        end
        tagged = true
      end

      case repo
        when 'spaced-ed'
          branches = %w{master edge qs-labs master-bugfixes edge-bugfixes}
        when 'QstreamIOS'
          branches = %w{master edge}
        else
          branches = %w{master}
      end

      branches.each do |br|
        next if br == current
        system("git update-ref refs/heads/#{br} remotes/origin/#{br}")
      end

      Open3.popen2e("git", "pull") {|i,oe,t|
        oe.each {|line|
          line.chomp!
          if /Fetching repository, done./ =~ line
          elsif /Already up-to-date./ =~ line
          elsif /Fetching (.+)/ =~ line
            #print "\033[2K\r#{line}"
          else
            puts line
          end
        }
      }
      # print "\033[2K\r"
    end
  end
end
