#!/usr/bin/env ruby
#
# File: git-synch-all
# Author: eweb
# Copyright eweb, 2013-2013
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Synch all workspaces
#

worktrees = %w{rails31 edge trove scratch}

worktrees.each do |wt|
  Dir.chdir("#{ENV['HOME']}/projects/qstream/#{wt}") do |dir|
    puts dir

    system("git remote update")

    branches = %w{rails31 master trove-master edge}

    current = `git rev-parse --abbrev-ref HEAD`.chomp

    puts "current [#{current}]"

    branches.each do |br|
      next if br == current
      system("git update-ref refs/heads/#{br} remotes/origin/#{br}")
    end

    system("git pull")
  end
end
