#!/usr/bin/env ruby
#
# File: git-synch
# Author: eweb
# Copyright eweb, 2013-2013
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Synch one workspace
#
system("git remote update")

branches = %w{rails31 master trove-master edge}

current = `git rev-parse --abbrev-ref HEAD`.chomp

puts "current [#{current}]"

branches.each do |br|
  next if br == current
  system("git update-ref refs/heads/#{br} remotes/origin/#{br}")
end

system("git pull")
