#!/bin/bash

#
# File: run_group
# Author: eweb
# Copyright eweb, 2017-2017
# Contents:
#
# Date:          Author:  Comments:
# 28th Oct 2017  eweb     #0008 run jenkins group
#

RUBYOPT="-W0" RAILS_ENV=test bundle exec rake ci:teardown ci:setup assets:precompile
RUBYOPT="-W0" RAILS_ENV=test PIPELINE=true time bundle exec parallel_test spec/ \
 -n $1 \
 --only-group $2 \
 --type rspec \
 --non-parallel \
 --test-options '--color --tty --fail-fast --format documentation --order defined'
