#!/usr/bin/env ruby
#
# File: tag-releases
# Author: eweb
# Copyright eweb, 2013-2018
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Tag releases
# 20th Aug 2014  eweb     #0008 More apps, display first tag
# 20th Sep 2014  eweb     #0008 analytics apps
#  7th Sep 2015  eweb     #0008 discover apps
# 16th Dec 2015  eweb     #0008 handle rollbacks
#  5th Apr 2016  eweb     #0008 heroku apps --all
# 28th Oct 2017  eweb     #0008 don't tag all apps
#  2nd Apr 2018  eweb     #0008 qs-bleedin is no more
#

apps = [ARGV[0]].compact

if apps.empty?
  all_apps = %x{heroku apps --all}
  all_apps.each_line do |app|
    app.chomp!
    app = app.split(' ')[0]
    if app =~ /^qs-/ || app =~ /^eweb-/
      #puts "[#{app}]"
      apps << app
    end
  end
end

apps.each do |app|
  next unless %w(qs-alpha qs-core-eu-1).include?(app)
  displayed = false
  releases = %x{heroku releases --app #{app}}
  releases.each_line do |release|
    #puts release
    fields = release.split(/\s+/)
    if fields[1] == 'Deploy'
      ver = fields[0]
      commit = fields[2]
      tag = "#{app}-#{ver}".upcase
      x = %x{git tag #{tag} #{commit} 2>&1}
      if x =~ /fatal: tag '#{tag}' already exists/
        puts tag unless displayed
        displayed = true
      elsif x =~ /fatal: Failed to resolve '.+' as a valid ref./
      elsif x =~ /fatal:/
        puts "#{app}: #{x}"
      else
        displayed = true
        puts "created tag #{tag} on commit #{commit}"
        x = %x{git push origin #{tag} 2>&1}
        if x =~ /fatal:/
          puts x
        end
      end
    elsif fields[1] == 'Rollback'
      ver = fields[0]
      commit = fields[3]
      old_tag = "#{app}-#{commit}".upcase
      tag = "#{app}-#{ver}".upcase
      x = %x{git tag #{tag} #{old_tag} 2>&1}
      if x =~ /fatal: tag '#{tag}' already exists/
        puts tag unless displayed
        displayed = true
      elsif x =~ /fatal: Failed to resolve '.+' as a valid ref./
      elsif x =~ /fatal:/
        puts "#{app}: #{x}"
      else
        displayed = true
        puts "created tag #{tag} on tag #{old_tag}"
        x = %x{git push origin #{tag} 2>&1}
        if x =~ /fatal:/
          puts x
        end
      end
    end
  end
end
