#!/usr/bin/env ruby
#
# File: tag-releases
# Author: eweb
# Copyright eweb, 2013-2014
# Contents:
#
# Date:          Author:  Comments:
#  5th Nov 2013  eweb     #0008 Tag releases
# 20th Aug 2014  eweb     #0008 More apps, display first tag
# 20th Sep 2014  eweb     #0008 analytics apps
#

apps = [ARGV[0]]

apps = %w{qs-alpha qs-bleedin qs-staging qs-analytics qs-analytics qs-analytics-2 qs-labs qs-demo qs-demo-launcher} if apps.compact.empty?

apps.each do |app|
  displayed = false
  releases = %x{heroku releases --app #{app}}
  releases.each_line do |release|
    #puts release
    fields = release.split(/\s+/)
    if fields[1] == 'Deploy'
      ver = fields[0]
      commit = fields[2]
      tag = "#{app}-#{ver}".upcase
      x = %x{git tag #{tag} #{commit} 2>&1}
      if x =~ /fatal: tag '#{tag}' already exists/
        puts tag unless displayed
        displayed = true
      elsif x =~ /fatal:/
        puts x
      else
        displayed = true
        puts "created tag #{tag} on commit #{commit}"
        x = %x{git push origin #{tag} 2>&1}
        if x =~ /fatal:/
          puts x
        end
      end
    end
  end
end
