#!/usr/bin/perl
#
# File: timezone_init.pl
# Author: eweb
# Copyright WBT Systems, 1995-2011
# Contents:
#
# Date:          Author:  Comments:
# 29th Sep 2010  eweb     #12612 scripts and exes
#  9th Mar 2011  eweb     #13033 WTimeZone.Display
#
use strict;
use File::Find;
use File::Temp qw/tempdir/;
use Getopt::Std;

sub osify($) {
  my ($path) = @_;
  if ( $^O eq "MSWin32" ) {
    $path =~ s!/!\\!g;
  }
  else {
    $path =~ s!\\!/!g;
  }
  return $path;
}


my %opts = ( d => undef(),
             m => undef(),
             n => undef(),
             p => undef(),
             b => undef(),
             v => undef(),
#             w => undef(),
#             o => undef(),
           );

if ( !getopts("d:m:n:p:b:v:", \%opts) or @ARGV > 1 ) {
  print STDERR "Unknown arg $ARGV[0]\n" if @ARGV > 0;
  Usage();
  exit;
}

sub Usage() {
  print "Usage: $0 <options>\n";
  print " -d drive\n";
  print " -m major\n";
  print " -n minor\n";
  print " -p point\n";
  print " -b build\n";
  print " -v verbose\n";
#  print " -w what (both|oracle|mssql|both)\n";
#  print " -o output\n";

}

my $verbose = $opts{v};
my $drive;
if ( defined( $opts{d} ) ) {
  $drive = $opts{d};
}

my $Year = (localtime(time))[5]+1900;

my $start = osify( "$drive/topclass/java/cnr/WebContent/WEB-INF/etc/zoneinfo-outlook/" );

my ($Major, $Minor, $Point, $Build, $Custom) = GetBuildNumber($drive);

if ( defined( $opts{m} ) ) {
  $Major = $opts{m};
}
if ( defined( $opts{n} ) ) {
  $Minor = $opts{n};
}
if ( defined( $opts{p} ) ) {
  $Point = $opts{p};
}
if ( defined( $opts{b} ) ) {
  $Build = sprintf( "%03d", $opts{b} );
}
my $mnpb = "$Major.$Minor.$Point.$Build";


my @directories_to_search = ( $start );

chdir( $start );

my @oralines;
my @sqllines;

find(\&wanted, @directories_to_search);

my $temp = tempdir();

mkdir( "$temp/ORACLE" );
mkdir( "$temp/MSSQL" );
mkdir( "$temp/MSSQL/Extra" );

open( ORA, ">$temp/ORACLE/timezone_init.sql" );
open( SQL, ">$temp/MSSQL/Extra/timezone_init.sql" );
sqlheader();
foreach ( sort( @oralines ) ) {
  print ORA $_;
}
foreach ( sort( @sqllines ) ) {
  print SQL $_;
}
sqlfooter();
close( ORA );
close( SQL );

sub wanted {
  #$File::Find::dir  = /some/path/
  #$_                = foo.ext
  #$File::Find::name = /some/path/foo.ext

  my $file = $_;
  my $path = $File::Find::name;

  if ( $file eq "." or $file eq ".." ) {
  }
  elsif ( -e $file and $file =~ /\.ics$/ ) {
    my $name = $path;
    $name =~ s!\.ics$!!;
    $name =~ s!^\Q$start\E[\\/]!!;
    my $offset = "+00:00";
    if ( open( ICS, $path ) ) {
      my $standard;
      while ( <ICS> ) {
        if ( /TZOFFSETTO:(.+)/ and $standard ) {
          $offset = $1;
          if ( $offset =~ /^([-+])([0-9][0-9])([0-9][0-9])$/ ) {
            $offset = "$1$2:$3";
          }
          else {
            print "-- Strange offset $offset\n";
          }
        }
        elsif ( /BEGIN:DAYLIGHT/ ) {
          $standard = undef;
        }
        elsif ( /BEGIN:STANDARD/ ) {
          $standard = 1;
        }
      }
      close( ICS );
    }
    @oralines = ( @oralines, "  INSERT INTO WTimeZone( WShortName, WOffset, WShow ) SELECT '$name', '$offset', 1 FROM DUAL WHERE NOT EXISTS ( SELECT NULL FROM WTimeZone WHERE WShortName = '$name');\n" );
    @sqllines = ( @sqllines, "  INSERT INTO WTimeZone( WShortName, WOffset, WShow ) SELECT '$name', '$offset', 1 WHERE NOT EXISTS ( SELECT NULL FROM WTimeZone WHERE WShortName = '$name');\n" );
  }
}

sub sqlheader() {
  print ORA "--\n";
  print ORA "-- File: timezone_init.sql\n";
  print ORA "-- Author: rger\n";
  print ORA "-- Warning: This file was generated by a perl script.\n";
  print ORA "-- Copyright WBT Systems, 1995-$Year\n";
  print ORA "-- Content: Time Zones Initialization;\n";
  print ORA "--\n";
  print ORA "-- Date:          Author:   Comments:\n";
  print ORA "--\n";
  print ORA "COLUMN DUMMY_TITLE NOPRINT\n";
  print ORA "\n";
  print ORA "TTITLE LEFT COL 3 '-- ============================================================ --' SKIP 1 -\n";
  print ORA "       LEFT COL 3 '-- File: timezone_init.sql                                      --' SKIP 1 -\n";
  print ORA "       LEFT COL 3 '-- ============================================================ --' SKIP 2\n";
  print ORA "\n";
  print ORA "SELECT NULL AS DUMMY_TITLE\n";
  print ORA "FROM DUAL\n";
  print ORA "/\n";
  print ORA "\n";
  print ORA "TTITLE OFF\n";
  print ORA "\n";
  print ORA "--================================================================================\n";
  print ORA "-- Time Zones;\n";
  print ORA "--================================================================================\n";
  print ORA "BEGIN\n";

  print SQL "--\n";
  print SQL "-- File: timezone_init.sql\n";
  print SQL "-- Author: rger\n";
  print SQL "-- Warning: This file was generated by a perl script.\n";
  print SQL "-- Copyright WBT Systems, 1995-$Year\n";
  print SQL "-- Content: Time Zones Initialization;\n";
  print SQL "--\n";
  print SQL "-- Date:          Author:   Comments:\n";
  print SQL "--\n";
  print SQL "\n";
  print SQL "SET NOCOUNT ON\n";
  print SQL "GO\n";
  print SQL "\n";
  print SQL "PRINT '============================';\n";
  print SQL "PRINT 'File: timezone_init.sql';\n";
  print SQL "PRINT '============================';\n";
  print SQL "PRINT '';\n";
  print SQL "PRINT '-- ------------------------------------------------------------------------------';\n";
  print SQL "GO\n";
  print SQL "\n";
  print SQL "--================================================================================\n";
  print SQL "-- Time Zones;\n";
  print SQL "--================================================================================\n";
  print SQL "BEGIN\n";
  print SQL "\n";
}

sub sqlfooter() {
  print ORA "  UPDATE WTimeZone SET WDisplay = WShortName WHERE WDisplay IS NULL;\n";
  print ORA "END;\n";
  print ORA "/\n";
  print ORA "\n";
  print ORA "COMMIT\n";
  print ORA "/\n";
  print ORA "\n";
  print ORA "PROMPT 'INSTALL --> TimeZone table initialized'\n";
  print ORA "\n";
  print ORA "--==============================================================================\n";
  print ORA "--                               Update Config\n";
  print ORA "--==============================================================================\n";
  print ORA "EXECUTE updateConfig('TIMEZONE_INIT', '$Major.$Minor.$Point.$Build' )\n";
  print ORA "/\n";


  print SQL "  UPDATE WTimeZone SET WDisplay = WShortName WHERE WDisplay IS NULL OR WDisplay = '';\n";
  print SQL "END;\n";
  print SQL "GO\n";
  print SQL "\n";
  print SQL "--==============================================================================\n";
  print SQL "--                               Update Config\n";
  print SQL "--==============================================================================\n";
  print SQL "EXECUTE updateConfig N'TIMEZONE_INIT', N'$Major.$Minor.$Point.$Build';\n";
  print SQL "GO\n";

}

sub GetBuildNumber($) {
  print "GetBuildNumber(@_)\n" if ( $verbose );
  my ($Major, $Minor, $Point, $Build, $Custom);

  my ($drive) = @_;

  my $BuildNoFile = "$drive/topclass/oracle/topclass/sources/buildno.h";
  if ( ! -e $BuildNoFile ) {
    my $VersionInfoFile = "$drive/topclass/oracle/topclass/sources/versioninfo.h";
    if ( -e $VersionInfoFile ) {
      $BuildNoFile = $VersionInfoFile;
    }
    else {
      my $NeoBuildNoFile = "$drive/topclass/neo/sources/buildno.h";
      if ( -e $NeoBuildNoFile ) {
        $BuildNoFile = $NeoBuildNoFile;
      }
      else {
        my $VersionInfoFile = "$drive/topclass/neo/sources/versioninfo.h";
        if ( -e $VersionInfoFile ) {
          $BuildNoFile = $VersionInfoFile;
        }
      }
    }
  }

  $BuildNoFile = osify($BuildNoFile);
  print "$BuildNoFile\n" if ( $verbose );

  if ( !open( BUILDNO, $BuildNoFile ) ) {
    print "**** Cannot open file $BuildNoFile for reading\n";
    return;
  }

  while ( <BUILDNO> ) {
    if ( /\#define BUILDNUMBER +([0-9]+)/ ) {
      $Build = $1;
    }
    elsif ( /\#define MAJORREVISION +([0-9]+)/ ) {
      $Major = $1;
    }
    elsif ( /\#define MINORREVISION +([0-9]+)/ ) {
      $Minor = $1;
    }
    elsif ( /\#define POINTREVISION +([0-9]+)/ ) {
      $Point = $1;
    }
    elsif ( /\#define BUILDINFO _TEXT\(\"(.*)\"\)/ ) {
      $Custom = $1;
    }
    elsif ( /\#define BUILDINFO \"(.*)\"/ ) {
      $Custom = $1;
    }
  }
  close BUILDNO;

  $Build = sprintf("%03d", $Build);
  return ($Major, $Minor, $Point, $Build, $Custom);
}

my $scripts = osify("$drive/topclass/oracle/topclass/Scripts" );

run( "ecopy -w -n- -r -s $temp -d $scripts *.sql -x *.bak" );

sub run($) {
  my $cmd = shift;
  print "cmd: $cmd\n";
  system( $cmd );
}
