#!/usr/bin/env zsh

#
# File: update
# Author: eweb
# Copyright eweb, 2021-2025
# Contents: update the machine after a period of inactivity
#
# Date:          Author:  Comments:
#  5th Jun 2021  eweb     #0008 update after inactivity
#  8th Oct 2021  eweb     #0008 get latest bundler & launch instaweb
#  8th Dec 2021  eweb     #0008 don't launch instaweb if already running
#  5th Apr 2023  eweb     #0008 accounts switch to main
# 21st Apr 2023  eweb     #0008 handle upstream remotes
# 21st Jun 2023  eweb     #0008 fetching and rebasing
# 19th Jan 2025  eweb     #0008 disambiguate between branches and origins
#

# bash needed echo -e "..."

(cd ~/bin
 # gem update rubygems
 gem update --system
 # rvm @global do gem update rubygems
 gem install bundler
 # bundle update --bundler
)

for dir in ~/bin ~/accounts/main
do
  echo "\033[32m$dir\033[0m" &&
  cd "$dir" &&
  test -d .git &&
  git fetch --all &&
  git pull &&
  test -f Gemfile &&
  bundle --quiet
done

for dir in ~/projects/*
do
  test -d "$dir" &&
  echo "\033[32m$dir\033[0m" &&
  cd "$dir" &&
  test -d .git &&
  if [[ -d .git/refs/remotes ]]; then
    git fetch --all &&
    git pull
  fi
  if [[ -f .git/refs/remotes/upstream/main ]]; then
    git checkout main
    git fetch upstream main:upstream
    git rebase --autostash heads/upstream
    # git push --force
  fi
  if [[ -f .git/refs/remotes/upstream/master ]]; then
    git checkout master
    git fetch upstream master:upstream
    git rebase --autostash heads/upstream
    # git push --force
  fi
done

for dir in ~/projects/acc/*/
do
  echo "\033[32m$dir\033[0m" &&
  cd "$dir" &&
  test -f Gemfile &&
  bundle --quiet
done

for dir in ~/projects/quest/*
do
  test -d "$dir" &&
  echo "\033[32m$dir\033[0m" &&
  cd "$dir" &&
  test -d .git &&
  git fetch --all &&
  git pull
done

for dir in ~/projects/qstream/*
do
  test -d "$dir" &&
  echo "\033[32m$dir\033[0m" &&
  cd "$dir" &&
  test -d .git &&
  git fetch --all &&
  git pull
done

# brew update
# brew upgrade

(lsof -i :1234 || git -C ~/projects/acc instaweb)
